name: package_template
channels:
- conda-forge
- defaults
- franklab
- edeno
dependencies:
- python>=3.9,<3.10
- numpy<1.24
- scipy
- scikit-learn
- matplotlib
- pandas
- jupyterlab
- pydotplus
- pyfftw<=0.12.0
- pytest
- pytest-cov
- black
- isort
- pip
- pip:
  - spyglass-neuro